name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
      env:
        FFLOGS_V1_APIKEY: ${{ secrets.FFLOGS_V1_APIKEY }}